@import gg.jte.Content
@param Content content

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="/styles/index.css" />
    <title>ProjectTeam</title>
</head>
<body>
<nav>
    <div class="navbar">
        <a href="/project">О проекте</a>
        <a href="/team">Команда</a>
        <a href="/reviews">Отзывы</a>
        <a href="/aboutUs">Вопросы && Ответы</a>
    </div>
</nav>
<main>${content}</main>
<footer class="footer">
    <p>© 2026 Some Project Team</p>
    <a href="https://github.com/NeoEmo">GitHub</a>
</footer>
</body>
</html>